### ISSUE TITLE
Comparison with other attributes?

### ISSUE THREAD

**Issue by natebird** [vapor/validation#32]
Is it possible to compare two attributes? I have two dates and one of the dates should be before the other. I'm going to do some user-facing validation on the client side but a model validation would be great too.

**Comment by grundoon** [comment]
Sure, there are several forms of custom `Validation` available, including this one passing the entire model into the validation closure: https://api.vapor.codes/validation/latest/Validation/Structs/Validations.html#/s:10Validation11ValidationsV3addySS_yxKctF

```swift
try validations.add("dates are ordered") { model in
    guard model.date1 <= model.date2 else {
        throw ...
    }
}
